"use client";

import { useState } from "react";
import { FiDownload, FiLoader, FiFileText, FiCalendar } from "react-icons/fi";
import { Button } from "@/components/ui/button";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import { PageHeader } from "@/components/shared/page-header";
import { Progress } from "@/components/ui/progress";

/* ─── Mock Generated Reports ─────────────────────────────────────────────── */

const reports = [
  { name: "Weekly Verification Summary",   type: "PDF",   generatedBy: "Rohit Admin", generatedAt: "18 May 2026, 09:00 AM", size: "1.2 MB" },
  { name: "Agent Performance Report",      type: "Excel", generatedBy: "Rohit Admin", generatedAt: "17 May 2026, 05:30 PM", size: "845 KB" },
  { name: "Branch Coverage Report",        type: "PDF",   generatedBy: "Rohit Admin", generatedAt: "16 May 2026, 11:00 AM", size: "2.1 MB" },
  { name: "Monthly Cases Audit Export",    type: "Excel", generatedBy: "Rohit Admin", generatedAt: "15 May 2026, 06:00 PM", size: "3.4 MB" },
];

/* ─── Reports Page ───────────────────────────────────────────────────────── */

export default function ReportsPage() {
  const [reportType, setReportType] = useState("");
  const [format, setFormat] = useState("");
  const [generating, setGenerating] = useState(false);
  const [genProgress, setGenProgress] = useState(0);

  function handleGenerate() {
    setGenerating(true);
    setGenProgress(0);
    let p = 0;
    const iv = setInterval(() => {
      p += Math.random() * 20 + 10;
      if (p >= 100) { p = 100; clearInterval(iv); setTimeout(() => setGenerating(false), 500); }
      setGenProgress(Math.min(p, 100));
    }, 200);
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Generate and export verification and performance reports."
      />

      {/* Config Card */}
      <div className="card-flat p-6">
        <h3 className="text-[14px] font-semibold text-slate-900 mb-5" style={{ fontFamily: "var(--font-plus-jakarta)" }}>
          Generate New Report
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-5">
          <Select value={reportType} onValueChange={(v) => v && setReportType(v)}>
            <SelectTrigger>
              <SelectValue placeholder="Report type…" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="weekly">Weekly Verification Summary</SelectItem>
              <SelectItem value="agent">Agent Performance</SelectItem>
              <SelectItem value="branch">Branch Coverage</SelectItem>
              <SelectItem value="audit">Cases Audit Export</SelectItem>
            </SelectContent>
          </Select>
          <div className="flex items-center gap-2 border border-border rounded-lg px-3 py-2 text-sm text-slate-500 cursor-pointer hover:border-slate-300">
            <FiCalendar className="w-4 h-4 shrink-0 text-slate-400" />
            <span>12 May – 18 May 2026</span>
          </div>
          <Select value={format} onValueChange={(v) => v && setFormat(v)}>
            <SelectTrigger>
              <SelectValue placeholder="Format…" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="pdf">PDF Document</SelectItem>
              <SelectItem value="excel">Excel Spreadsheet</SelectItem>
            </SelectContent>
          </Select>
        </div>

        {generating ? (
          <div className="space-y-2">
            <div className="flex justify-between text-xs text-slate-500">
              <span>Generating report…</span>
              <span>{Math.round(genProgress)}%</span>
            </div>
            <Progress value={genProgress} className="h-2" />
          </div>
        ) : (
          <Button
            onClick={handleGenerate}
            disabled={!reportType || !format}
            className="bg-[--color-brand-900] hover:bg-[--color-brand-800] text-white gap-2"
          >
            <FiFileText className="w-4 h-4" />
            Generate Report
          </Button>
        )}
      </div>

      {/* Previous Reports */}
      <div className="card-flat overflow-hidden">
        <div className="px-5 py-4 border-b border-border">
          <h3 className="text-[14px] font-semibold text-slate-900" style={{ fontFamily: "var(--font-plus-jakarta)" }}>
            Generated Reports
          </h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border bg-slate-50">
                {["Report Name", "Format", "Generated By", "Date & Time", "Size", ""].map((h) => (
                  <th key={h} className="px-5 py-3 text-left text-xs font-medium text-slate-400 uppercase tracking-wider whitespace-nowrap">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {reports.map((r) => (
                <tr key={r.name} className="hover:bg-slate-50 transition-colors">
                  <td className="px-5 py-3.5">
                    <div className="flex items-center gap-2">
                      <FiFileText className="w-4 h-4 text-slate-300 shrink-0" />
                      <span className="font-medium text-slate-900">{r.name}</span>
                    </div>
                  </td>
                  <td className="px-5 py-3.5">
                    <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${r.type === "PDF" ? "bg-rose-50 text-rose-700" : "bg-teal-50 text-teal-700"}`}>
                      {r.type}
                    </span>
                  </td>
                  <td className="px-5 py-3.5 text-slate-500">{r.generatedBy}</td>
                  <td className="px-5 py-3.5 text-slate-400 text-xs font-mono whitespace-nowrap">{r.generatedAt}</td>
                  <td className="px-5 py-3.5 text-slate-400 text-xs">{r.size}</td>
                  <td className="px-5 py-3.5">
                    <Button variant="ghost" size="sm" className="gap-1.5 text-xs text-[--color-brand-900]">
                      <FiDownload className="w-3.5 h-3.5" />
                      Download
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
