"use client";

import { useState, useEffect } from "react";
import { FiDownload, FiFileText, FiCalendar, FiChevronDown } from "react-icons/fi";
import { Button } from "@/components/ui/button";
import {
  Select, SelectContent, SelectItem, SelectTrigger, SelectValue,
} from "@/components/ui/select";
import {
  Popover, PopoverContent, PopoverTrigger,
} from "@/components/ui/popover";
import { PageHeader } from "@/components/shared/page-header";
import { Progress } from "@/components/ui/progress";
import { cn } from "@/lib/utils";
import { toast } from "sonner";
import { getReportsApi, generateReportApi } from "@/lib/api";

/* ─── Data ───────────────────────────────────────────────────────────────── */

const DATE_RANGES = [
  { label: "This Week",  value: "07 Jul – 13 Jul 2026" },
  { label: "Last Week",  value: "30 Jun – 06 Jul 2026" },
  { label: "This Month", value: "01 Jul – 09 Jul 2026" },
  { label: "Last Month", value: "01 Jun – 30 Jun 2026" },
];

const REPORT_TYPES = [
  { value: "weekly",  label: "Weekly Verification Summary" },
  { value: "agent",   label: "Agent Performance Report" },
  { value: "branch",  label: "Branch Coverage Report" },
  { value: "audit",   label: "Cases Audit Export" },
];

const FORMATS = [
  { value: "pdf",   label: "PDF Document" },
  { value: "excel", label: "Excel Spreadsheet" },
];

function downloadBlob(content: string, filename: string, mime = "text/plain") {
  const blob = new Blob([content], { type: mime });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement("a");
  a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}

/* ─── Reports Page ───────────────────────────────────────────────────────── */

export default function ReportsPage() {
  const [reportType, setReportType] = useState("");
  const [format, setFormat]         = useState("");
  const [dateRange, setDateRange]   = useState(DATE_RANGES[0]);
  const [calOpen, setCalOpen]       = useState(false);
  const [generating, setGenerating] = useState(false);
  const [genProgress, setGenProgress] = useState(0);
  const [reports, setReports]       = useState<any[]>([]);

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const res = await getReportsApi();
      setReports(res.data.data);
    } catch (err) {
      toast.error("Failed to fetch reports");
    }
  };

  function handleGenerate() {
    if (!reportType || !format) {
      toast.error("Please select a report type and format.");
      return;
    }
    setGenerating(true);
    setGenProgress(0);
    let p = 0;
    const iv = setInterval(() => {
      p += Math.random() * 20 + 10;
      if (p >= 100) {
        p = 100;
        clearInterval(iv);
        
        generateReportApi({ reportType, format, dateRange: dateRange.value })
          .then(() => {
             toast.success("Report generated successfully!");
             fetchReports();
          })
          .catch(() => toast.error("Failed to generate report"))
          .finally(() => {
            setGenerating(false);
            setReportType("");
            setFormat("");
          });
      }
      setGenProgress(Math.min(p, 100));
    }, 180);
  }

  function handleDownload(r: any) {
    const content = `Report: ${r.name}\nFormat: ${r.type}\nGenerated By: ${r.generatedBy}\nDate: ${r.generatedAt}\n\n[Sample report data — connect to backend for real export]`;
    const ext = r.type === "PDF" ? "txt" : "csv";
    downloadBlob(content, `${r.name.replace(/\s+/g, "_")}.${ext}`);
    toast.success(`Downloading ${r.name}`);
  }

  return (
    <div className="space-y-6">
      <PageHeader
        title="Reports"
        description="Generate and export verification and performance reports."
      />

      {/* ── Generate New Report ── */}
      <div className="card-flat p-6">
        <h3 className="text-[14px] font-semibold text-slate-900 mb-5" style={{ fontFamily: "var(--font-plus-jakarta)" }}>
          Generate New Report
        </h3>
        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-5">
          {/* Report Type */}
          <Select value={reportType} onValueChange={(v) => v && setReportType(v)}>
            <SelectTrigger>
              <SelectValue placeholder="Report type…" />
            </SelectTrigger>
            <SelectContent>
              {REPORT_TYPES.map((r) => (
                <SelectItem key={r.value} value={r.value}>{r.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>

          {/* Date Range Picker */}
          <Popover open={calOpen} onOpenChange={setCalOpen}>
            <PopoverTrigger className="flex items-center gap-2 border border-[#E2E8F0] rounded-lg px-3 py-2 text-sm text-slate-600 bg-white hover:border-slate-300 outline-none transition-colors">
              <FiCalendar className="w-4 h-4 text-slate-400 shrink-0" />
              <span className="flex-1 text-left">{dateRange.value}</span>
              <FiChevronDown className="w-3.5 h-3.5 text-slate-400 shrink-0" />
            </PopoverTrigger>
            <PopoverContent align="start" className="w-52 p-1">
              <p className="text-[10px] font-semibold text-slate-400 uppercase tracking-wider px-2 py-1.5">
                Select Range
              </p>
              {DATE_RANGES.map((r) => (
                <button
                  key={r.label}
                  onClick={() => { setDateRange(r); setCalOpen(false); }}
                  className={cn(
                    "w-full text-left px-3 py-2 rounded-lg text-sm transition-colors",
                    dateRange.label === r.label
                      ? "bg-blue-50 text-[#1E3A5F] font-semibold"
                      : "text-slate-700 hover:bg-slate-50"
                  )}
                >
                  {r.label}
                  <span className="block text-[10px] text-slate-400 font-normal mt-0.5">{r.value}</span>
                </button>
              ))}
            </PopoverContent>
          </Popover>

          {/* Format */}
          <Select value={format} onValueChange={(v) => v && setFormat(v)}>
            <SelectTrigger>
              <SelectValue placeholder="Format…" />
            </SelectTrigger>
            <SelectContent>
              {FORMATS.map((f) => (
                <SelectItem key={f.value} value={f.value}>{f.label}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {generating ? (
          <div className="space-y-2">
            <div className="flex justify-between text-xs text-slate-500">
              <span>Generating report…</span>
              <span>{Math.round(genProgress)}%</span>
            </div>
            <Progress value={genProgress} className="h-2" />
          </div>
        ) : (
          <Button
            onClick={handleGenerate}
            disabled={!reportType || !format}
            className="text-white gap-2 disabled:opacity-40"
            style={{ background: "#1E3A5F" }}
          >
            <FiFileText className="w-4 h-4" />
            Generate Report
          </Button>
        )}
      </div>

      {/* ── Generated Reports Table ── */}
      <div className="card-flat overflow-hidden">
        <div className="px-5 py-4 border-b border-border">
          <h3 className="text-[14px] font-semibold text-slate-900" style={{ fontFamily: "var(--font-plus-jakarta)" }}>
            Generated Reports
          </h3>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border bg-slate-50">
                {["Report Name", "Format", "Generated By", "Date & Time", "Size", ""].map((h) => (
                  <th key={h} className="px-5 py-3 text-left text-xs font-medium text-slate-400 uppercase tracking-wider whitespace-nowrap">
                    {h}
                  </th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-border">
              {reports.map((r, i) => (
                <tr key={i} className="hover:bg-slate-50 transition-colors">
                  <td className="px-5 py-3.5">
                    <div className="flex items-center gap-2">
                      <FiFileText className="w-4 h-4 text-slate-300 shrink-0" />
                      <span className="font-medium text-slate-900">{r.name}</span>
                    </div>
                  </td>
                  <td className="px-5 py-3.5">
                    <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${r.type === "PDF" ? "bg-rose-50 text-rose-700" : "bg-teal-50 text-teal-700"}`}>
                      {r.type}
                    </span>
                  </td>
                  <td className="px-5 py-3.5 text-slate-500">{r.generatedBy}</td>
                  <td className="px-5 py-3.5 text-slate-400 text-xs font-mono whitespace-nowrap">{r.generatedAt}</td>
                  <td className="px-5 py-3.5 text-slate-400 text-xs">{r.size}</td>
                  <td className="px-5 py-3.5">
                    <Button
                      variant="ghost" size="sm"
                      className="gap-1.5 text-xs font-semibold"
                      style={{ color: "#1E3A5F" }}
                      onClick={() => handleDownload(r)}
                    >
                      <FiDownload className="w-3.5 h-3.5" />
                      Download
                    </Button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
